added Ansible files and screenshot/urls.txt

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,6 +20,9 @@ jobs:
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
+      - run:
+          name: stop job
+          command: exit 1
 
   build-backend:
     docker:
@@ -103,30 +106,57 @@ jobs:
     steps:
       - checkout
       - run:
+          name: install tar and gzip to use persist_to_workspace
+          command: yum -y install tar gzip
+      - run:
           name: Ensure back-end infrastructure exists
           command: >
             aws cloudformation deploy
             --template-file .circleci/files/backend.yml
             --tags Project="udapeople"
             --stack-name "jims-back-end-${CIRCLE_WORKFLOW_ID:0:7}"
-            --parameter-overrides ID=jimsID-${CIRCLE_WORKFLOW_ID:0:7}
+            --parameter-overrides ID="jimsID-${CIRCLE_WORKFLOW_ID:0:7}"
       - run:
-          name: Ensure front-end infrastructure exist
+          name: Ensure front-end infrastructure exists
           command: >
             aws cloudformation deploy
-              --template-file .circleci/files/frontend.yml
-              #--tags project=your-tag
-              # --stack-name "jims-front-end-${CIRCLE_WORKFLOW_ID:0:7}"
-              # --parameter-overrides ID=jimsID-${CIRCLE_WORKFLOW_ID:0:7}
+            --template-file .circleci/files/frontend.yml
+            --tags Project=frontend
+            --stack-name "jims-front-end-${CIRCLE_WORKFLOW_ID:0:7}"
+            --parameter-overrides ID="jimsID-${CIRCLE_WORKFLOW_ID:0:7}"
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-            echo '[web]' > inventory.txt
-            aws ec2 describe-instances --filter "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].[PublicIpAddress]" --output=text >> inventory.txt
+            echo '[web]' > project/.circleci/ansible/inventory.txt
+            aws ec2 describe-instances --filter "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].[PublicIpAddress]" --output=text >> project/.circleci/ansible/inventory.txt
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
+      # Here's where you will add some code to rollback on failure
+      - run:
+        name: on failure delete stacks that were created
+        command: >
+          aws cloudformation delete-stack --stack-name "jims-back-end-${CIRCLE_WORKFLOW_ID:0:7}"
+          aws cloudformation delete-stack --stack-name "jims-front-end-${CIRCLE_WORKFLOW_ID:0:7}"
+        when: on_fail
+
+  configure-infrastructure:
+    docker:
+      - image: python:3.8.6-alpine3.12
+    steps:
+      - checkout
+      - add_ssh_keys:
+          fingerprints:
+            - "00:31:ee:87:23:d8:65:e0:80:39:73:0e:ab:0e:98:d8"
+      - attach_workspace:
+          at: ~/
+      -- run:
+          name: install dependencies
+          command: apk add --update ansible
+      - run:
+          name: configure server on AWS
+          command: ansible-playbook -i project/.circleci/ansible/inventory.txt project/.circleci/ansible/configure-server.yml
       # Here's where you will add some code to rollback on failure
 
 workflows:
@@ -155,3 +185,6 @@ workflows:
           filters:
             branches:
               only: master
+      - configure-infrastructure:
+          requires:
+            - deploy-infrastructure
